name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: npm install
          run: npm ci
        - name: run unit tests
          run: npm test
        - name: Build and push the image
          run: |
            docker login --username danespn --password ${{secrets.ACCESS_TOKEN}} ghcr.io
            docker build -t ghcr.io/danespn/arithmetic-service:latest --file Dockerfile .
            docker push ghcr.io/danespn/arithmetic-service:latest
        - name: Publish the image to azure container registry
          run: |
            docker login --username danespenPracticum15 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} danespenPracticum15.azurecr.io
            docker tag ghcr.io/danespen/arithmetic-services:1 practicum15/azurcr.io/arithmetic-services:1
            docker push practicum15.azurcr.io/arithmetic-services:1
          